// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommentLinks
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCommentLinksPackageString = "e1724685-50af-49aa-9d96-ff26a69cc1c9";
        public static Guid guidCommentLinksPackage = new Guid(guidCommentLinksPackageString);

        public const string guidCshtmlCodeEditorString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public static Guid guidCshtmlCodeEditor = new Guid(guidCshtmlCodeEditorString);

        public const string GuidVisualStudioXAMLWindowContextMenuString = "4c87b692-1202-46aa-b64c-ef01faec53da";
        public static Guid GuidVisualStudioXAMLWindowContextMenu = new Guid(GuidVisualStudioXAMLWindowContextMenuString);

        public const string guidCommentLinksPackageCmdSetString = "8b7f9d00-fcc1-4b0f-a951-3d63273c87de";
        public static Guid guidCommentLinksPackageCmdSet = new Guid(guidCommentLinksPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int IDVisualStudioXAMLWindowContextMenu = 0x0103;
        public const int CodeContextGroup = 0x1100;
        public const int CodeContextMenu = 0x1200;
        public const int CodeContextMenuGroup = 0x1300;
        public const int LinkToFileCommandId = 0x0100;
        public const int LinkToLineCommandId = 0x0200;
        public const int LinkToSelectionCommandId = 0x0300;
    }
}