// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommentLinks
{
    internal sealed partial class Vsix
    {
        public const string Id = "CommentLinks.bd536c05-2af9-4995-b067-56fa2bb88e31";
        public const string Name = "Comment Links";
        public const string Description = @"Create links in comments between any files.";
        public const string Language = "en-US";
        public const string Version = "3.0.2";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
